[package]
description = "Trident 3 kernel module"
documentation.workspace = true
edition.workspace = true
name = "trident3-main"
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["staticlib"]
name = "t3_main"
path = "index.rs"
