[package]
name = "ff-shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ffsh"
path = "index.rs"

[dependencies]
base = { path = "../../lib/base", version = "*" }
